services:
  diffusion_policy:
    image: diffusion_policy
    build: .
    container_name: diffusion_policy_hwanhee
    volumes:
      - ~/workspace:/workspace
      - /home/tung/workspace/vla_bench/diffusion_policy:/home/tung/workspace/vla_bench/diffusion_policy
    environment:
      - HOST_UID=1001
    shm_size: '8gb'
    tty: true
    stdin_open: true
    command: /bin/bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]